default_platform(:ios)

platform :ios do
  # ENV overrides
  ENV['SCAN_DERIVED_DATA_PATH'] = 'DerivedData'
  ENV['GYM_DERIVED_DATA_PATH'] = 'DerivedData'

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "GuildKitDemo")
    upload_to_testflight
  end

  desc "Tests the app"
  lane :build_and_test do
    build_for_testing
    unit_tests
  end

  desc "Builds the app and outputs binaries"
  lane :build do 
    build_app(
      export_method: 'development',
      configuration: 'Debug',
      output_directory: './',
      skip_archive: true,
      destination: 'generic/platform=iOS Simulator',
      cloned_source_packages_path: "SourcePackages"
    )
  end

  desc "Build for testing"
  lane :build_for_testing do 
    run_tests(
      build_for_testing: true,
    )
  end

  desc "Runs tests"
  lane :unit_tests do 
    run_tests(
      test_without_building: true,
    )
  end
end
